deploy_env: ${DEPLOY_ENV:dev} # since there's a default, define this once

martha:
  bondUrl: https://broad-bond-${deploy_env}.appspot.com
  samUrl: https://sam.dsde-${deploy_env}.broadinstitute.org
  externalcredsUrl: https://externalcreds.dsde-${deploy_env}.broadinstitute.org

  hosts:
    bioDataCatalyst: staging.gen3.biodatacatalyst.nhlbi.nih.gov
    crdc: nci-crdc-staging.datacommons.io
    kidsFirst: gen3staging.kidsfirstdrc.org
    theAnvil: staging.theanvil.io


server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: martha

  jackson.serialization.indent_output: true

  main.banner-mode: off

  profiles.include:
    - ${deploy-env}

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

---
spring.config.activate.on-profile: prod
martha:
  hosts:
    bioDataCatalyst: gen3.biodatacatalyst.nhlbi.nih.gov
    crdc: nci-crdc.datacommons.io
    kidsFirst: data.kidsfirstdrc.org
    theAnvil: gen3.theanvil.io
