deploy_env: ${DEPLOY_ENV:dev} # since there's a default, define this once

martha:
  bondUrl: https://broad-bond-${deploy_env}.appspot.com
  samUrl: https://sam.dsde-${deploy_env}.broadinstitute.org
  externalcredsUrl: https://externalcreds.dsde-${deploy_env}.broadinstitute.org

  hosts:
    bioDataCatalyst: staging.gen3.biodatacatalyst.nhlbi.nih.gov
    crdc: nci-crdc-staging.datacommons.io
    kidsFirst: gen3staging.kidsfirstdrc.org
    theAnvil: staging.theanvil.io

  drsProviders:
    bioDataCatalyst:
      name: BioData Catalyst (BDC)
      metadataAuth: false
      bondProvider: fence
      accessMethods:
        - type: gcs
          auth: fence_token
          fetchAccessUrl: false
    terraDataRepo:
      name: Terra Data Repo (TDR)
      metadataAuth: true
      bondProvider: null
      accessMethods:
        - type: gcs
          auth: current_request
          fetchAccessUrl: false
        - type: https
          auth: current_request
          fetchAccessUrl: true # Used for Azure
    kidsFirst:
      name: Gabriella Miller Kids First DRC
      metadataAuth: false
      bondProvider: kids_first
      accessMethods:
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    anvil:
      name: NHGRI Analysis Visualization and Informatics Lab-space (The AnVIL)
      metadataAuth: false
      bondProvider: anvil
      accessMethods:
        - type: gcs
          auth: fence_token
          fetchAccessUrl: false
    crdc:
      name: NCI Cancer Research / Proteomics Data Commons (CRDC / PDC)
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethods:
        - type: gcs
          auth: fence_token
          fetchAccessUrl: false
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    passport:
      name: Passport Test Provider
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethods:
        - type: gcs
          auth: passport
          fetchAccessUrl: false
          fallbackAuth: fence_token
        - type: s3
          auth: passport
          fetchAccessUrl: true
          fallbackAuth: fence_token

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: martha

  jackson.serialization.indent_output: true

  main.banner-mode: off

  profiles.include:
    - ${deploy-env}

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

---
spring.config.activate.on-profile: prod
martha:
  hosts:
    bioDataCatalyst: gen3.biodatacatalyst.nhlbi.nih.gov
    crdc: nci-crdc.datacommons.io
    kidsFirst: data.kidsfirstdrc.org
    theAnvil: gen3.theanvil.io
