server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: martha

  config.import: optional:classpath:rendered/hosts.yaml

  datasource: {}

  jackson.serialization.indent_output: true

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
