# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test

  deploy-staging:
    machine: true
    steps:
      # see https://cloud.google.com/sdk/gcloud/reference
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components update --quiet
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components install beta --quiet
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project broad-dsde-staging
      - run: echo $GCLOUD_FUNCTIONS_STAGING_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: deploy martha
          command: sudo /opt/google-cloud-sdk/bin/gcloud beta functions deploy martha_v1 --source https://source.developers.google.com/projects/broad-dsde-staging/repos/martha/moveable-aliases/dev --trigger-http

  deploy-prod:
    machine: true
    steps:
      # see https://cloud.google.com/sdk/gcloud/reference
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components update --quiet
      - run: sudo /opt/google-cloud-sdk/bin/gcloud components install beta --quiet
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project broad-dsde-staging
      - run: echo $GCLOUD_FUNCTIONS_PROD_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: deploy martha
          command: sudo /opt/google-cloud-sdk/bin/gcloud beta functions deploy martha_v1 --source https://source.developers.google.com/projects/broad-dsde-prod/repos/martha/moveable-aliases/master --trigger-http

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
